# Site settings
title:       随手一笔
email:       fansekey@gmail.com
author:      oxUnd
description: "某人的日常牢骚，写一些有的没的"
baseurl:     ""
url:         "https://www.orrafy.com"
date_format: "%b %-d, %Y"

# Google services
google_analytics:
google_verification:

# Optional features
animated:             false
show_related_posts:   false
show_post_footers:    false
show_social_icons:    true
ajaxify_contact_form: false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: feeddly

# Social icons
github_username: oxUnd
bitbucket_username:
stackoverflow_id:
twitter_username: 
linkedin_username:
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: false
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: false
share_twitter: false
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false

# Build settings
gems: [jekyll-paginate, jekyll-gist]
markdown : kramdown
markdown_ext : markdown,md,mdk
highlighter: rouge

# permalink:    pretty
permalink : /posts/:categories/:title
paginate:     25
sass:
  compressed: true
