name: ":)"
markdown: redcarpet
highlighter: 'pygments'
permalink: :title
exclude: [README.md, LICENSE, Makefile]

# Information for the Atom feed
gereksiz:
   author: "xiangshouding"
   email: "fansekey@gmail.com"

markdown: redcarpet
markdown_ext: markdown,md,mdk
redcarpet:
    extensions: ['fenced_code_blocks']
    
# sitemap
gems:
  - jekyll-sitemap
  
#########
source: .
destination: ../mysite