

name : "Xiang Shouding "
markdown : redcarpet
highlighter : 'pygments'
permalink : /posts/:categories/:title
exclude: ['README.md', 'LICENSE', 'Makefile']
include: ['./assets']

# Information for the Atom feed
gereksiz:
   author : "xiangshouding"
   email : "fansekey@gmail.com"

markdown : redcarpet
markdown_ext : markdown,md,mdk
redcarpet:
    extensions : ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
