#+TITLE: 2018-12-08-0x01
#+DATE: 2018-12-08 17:08:49
#+AUTHOR: 

* 2018-12-08-0x01

** 0x00
:PROPERTIES:
:CUSTOM_ID: x00
:END:
看到最早一次写点东西发布出来是在 2017 年，现在已经 2018
要过去了，整整一年多的时间，没有在博客上面留下一丁点记录。这着实跟我的意图相悖。在这
2018 年关将近的晚上，我打算随口唠叨几句。

唠叨的东西跟工作无关，大概随便写写，想到什么地方写什么。

** 0x01
:PROPERTIES:
:CUSTOM_ID: x01
:END:
现在我想到的是我的周末，我的周末自从把房子装修出来以后就变得有点不同。在当下这个房价贵到一定程度的社会大环境下，只能把房子买在开车
2 小时外的北京周边省市。大概也是在一个不怎么友好的场景下买下来这套房子。

当时买的时候就在想，等房子下来，我就把它卖掉换钱。当真的到手，在一个环境还不错的地方，不想把它出售，并好好装饰了一番。

就这么，每个周末我都会周五晚上开车从出租屋出发回家。这就算是身体的迁徙吧。

“迁徙而居”

有时候在工作日可能会期待回家，新小区，暖气足，也同样可以高速“飙车”。

每次过来，都会自己亲自做饭，这些工作是我家领导完成的，我参加的非常少。可能对于我来说，洗碗更合适。

我俩尝试了非常多的菜系做发，比如西北、东北、或者是湘菜不一而足，今天就吃了自捏的饺子。

喜欢这种过家家的感觉

** 0x02
:PROPERTIES:
:CUSTOM_ID: x02
:END:
同样我也开始琢磨一个事情，我打开了一本纸质书，我的身边的图书大多都是计算机图书。今天看了会儿《Unix
环境高级编程》。

当然，书是看不进去的，感觉书太沉，就拿起 PAD
搜一下，到底有没有电子版，最后在“多看”找到了最新的排版又美的电子版本。我想只有多看能做到这么又美的排版了。亚马逊的中国版本的电子书就是个笑话，除了小说。

随后，感觉自己的 PAD 屏幕分辨率不怎么行，有点懊悔当时买 小米4 这款小
PAD。可便宜，就当买了个玩具。

看书只是幌子，最大的乐趣就是通过琐碎的时间挥发掉这个周末的时间，我周末宁愿眼睛睁着浪费时间也不愿意把时间浪费在睡觉上。这大概就是我自己。

“瞎捣鼓”

这大概是我自己对自己又一个诠释吧。

在工作的时候，我是一门心思去工作的，可不要误解工作时候的我。

** 0x03
:PROPERTIES:
:CUSTOM_ID: x03
:END:
下午接到了一堆报警，报警没人处理，有点恼火。但毕竟处理问题是我自己的“天职”，上手就开始处理。

发现报警的信息跟实际信息根本对不上，有点惶恐，也同样气恼与基础设施太操蛋。心中默默问候了不知道多少人的工作到底是否到位。

“突如其来的报警”

这大概也是周末的一部分，同样这些报警匪夷所思，同样衬托我周末的生活，匪夷所思；

** 0x04
:PROPERTIES:
:CUSTOM_ID: x04
:END:
拿着这台 i7 处理器的电脑，准确点说是一台小米游戏本，在我这种 VIM
用得还算快速的人来说，这台电脑的键盘让人抓狂，根本不适合做为编码机器的游戏本，失去了它应该有的价值。

当时，想到要一台高性能的电脑，选了一直看好生态的小米游戏本，但用起来比
Surface 差不少，后续假设入电脑，还是找官方电脑比较合适。

“买了许多电子产品，但有时会后悔买这些”

同样是我周末的一部分。

今年尝试满足了自己所有的欲望，主要是搞了一堆的电子产品，手机无数。但用下来，能当主流机的没多少家。

苹果手机算一个，华为手机算一个，其他，那怕是单摄第一的 Pixel
系列，只能当玩具来看待，对 Google
跟中国当下网络下提供的服务颇为担心以及心塞。

** 0x05
:PROPERTIES:
:CUSTOM_ID: x05
:END:
盯着 60
多英寸的小米电视，看一部剧应该是一个还不错的选择，但，好看的剧也就那么多。

最近在看《将夜》，周末却不放，有点些许遗憾。

跟爱人一起看了一部腾讯拍的美食类纪录片，充分吊起自己的胃口，在市场买了许多食材，做了饺子和胡辣汤。

是的。

这大概就是我有很多事情要做的周末。

对。

这周是单周，明天还得上班呢，明天的大概还是会有很多会要参加。开始我新的一周工作。
