#+TITLE: "买了一台黑莓手机"
#+DATE: 2016-03-04 14:28:43 +0800
#+CATEGORIES: my
#+AUTHOR: 

* 2016-03-04-note-no.2

好久没上来写一下近况了，完全违背了我『随手一笔』的初衷。

前面的一个月回家过了个年还跟我家领导把婚礼给办了，农家婚礼颇具特色，等我有时间整理一下照片再一篇，今天我们先不谈这个。

今天的话题是，我上周末由于心中长草买了一台黑莓手机，从这台黑莓手机说起。

长草的过程，我回家以后家里面 500
块钱买的一款黑莓手机还健在，随便拿起来把玩了几分钟后觉着这键盘太有手感的，然后对黑莓顿觉好感，回北京后在闲鱼上各种找黑莓机器，看到
BlackBerry Passport 一下就被吸引住了。

心中长了草总得把这个给解决了，遂用各种理由向领导申请经费，然后就购得这块
Passport 2 代 （其实比一代就换了个皮）。

拿到手机后，确实被这胖家伙下了一跳，感觉一只手拿着真费劲，再加上领导在一旁吹风倍受打击，但把玩数日，发现好处不少，坏处也不少。

足够让我说上几千字的就是这块键盘了，从来没有在手机上打字这么爽过，随写了两篇使用体验，对了，一定要结合
BlackBerry 上的 Evernote。

- [[https://www.evernote.com/l/ACBgW8RNVTlFaJisoKHnk2yN8D4hFfp2rTg][黑莓手机使用感受]]
- [[https://www.evernote.com/l/ACAASA3OGCBKv6n28VpaZIb8AV6yqJ1IZaY][黑莓手机 Passport 应用篇]]

都是用这台黑莓机器写的，从来没想过能用手机写文章。主要是摸着那块键盘就停不下来了。

我在这两篇中已经把诸多优劣都说了，也是暂时位置体会到的，有兴趣可以看看。

我很迷恋电子产品，各种操作系统都体验过，WebOS、Ubuntu
touch、塞班、智能机、Android、iOS。如果说到内容消费非 iOS
类设备莫属，如果说到玩起来比较爽那可能就得 Linux
系列的操作系统的软件了，能各种刷机，可以有很多好玩的 App。

黑莓嘛，现在听说也 Android 了，不过我想很难
ROOT，如果硬件做得不好就没那么好玩了，不过还是看好那块键盘。

如果你也用了 BlackBerry OS 10，那么我们有话聊。
