name: Build and publish to pages
on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 1
    - name: build
      env:
        ENV: production
      uses: docker://silex/emacs:29.4-debian-ci
      if: github.event.deleted == false
      with:
        args: ./build.sh
    - name: deploy
      uses: peaceiris/actions-gh-pages@v4
      if: github.ref == 'refs/heads/master')
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
